spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/notesdb
    username: ${DB_USER:notes_user}
    password: ${DB_PASS:notes_pass}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASS:}

flyway:
  enabled: true
  locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: ["health", "metrics", "prometheus"]
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  security:
    enabled: false

sentry:
  dsn: ${SENTRY_DSN:}  # Secret from env var
  traces-sample-rate: 1.0
