spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notesdb
    username: notes_user
    password: notes_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  redis:
    host: localhost
    port: 6379
  security:
    user:
      name: admin
      password: adminpass

flyway:
  enabled: true
  locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.springframework: INFO


management:
  endpoints:
    web:
      exposure:
        include: ["health", "metrics", "prometheus"]
  endpoint:
    health:
      show-details: always
  security:
    enabled: false

sentry:
  dsn: ${SENTRY_DSN:}  # configure later
  traces-sample-rate: 1.0